# Generated by Django 4.2.11 on 2024-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_addpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='AddPost',
        ),
    ]
